### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by pedrohma** [trindadematheus/keybit#6]
Acessei o link do vercel para a aplicacao. Apos inserir o username e clicar em 'criar nova sala' obtive o seguinte erro de CORS:

![image](https://user-images.githubusercontent.com/6583751/116619787-c590ff00-a8f5-11eb-9d3c-95c1ce6a929f.png)

**Comment by trindadematheus** [comment]
E ai Pedro, blz? Eu estava utilizando o servidor Free da heroku e ele atingiu a capacidade por isso o front não estava conseguindo conectar, mas agora o jogo tem um servidor próprio em uma nova URL: https://keybit.wemakean.com/ Da uma jogada lá e se achar outro bug pode reportar aqui nas Issues, valeu 🎉

**Comment by pedrohma** [comment]
Seu projeto esta muito massa Matheus! 👍🏼
